export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';

export const SET_TEACHER_ACTIVE_CLASS = 'SET_TEACHER_ACTIVE_CLASS';
export const SET_TEACHER_CLASSES = 'SET_TEACHER_CLASSES';
export const SET_TEACHER_INFOBOX = 'SET_TEACHER_INFOBOX';
export const SET_TEACHER_ACTIVE_CLASS_STUDENT_VALUE_INDEX = 'SET_TEACHER_ACTIVE_CLASS_STUDENT_VALUE_INDEX';
export const SET_TEACHER_CLASS_STUDENT_VALUES = 'SET_TEACHER_CLASS_STUDENT_VALUES';
export const SET_TEACHER_ACTIVE_SECTION_SUBJECT = 'SET_TEACHER_ACTIVE_SECTION_SUBJECT';
export const UPDATE_TEACHER_CLASS_STUDENT_VALUES = 'UPDATE_TEACHER_CLASS_STUDENT_VALUES';
export const RESET_TEACHER_DEFAULTS = 'RESET_TEACHER_DEFAULTS';

export const SET_ADMIN_ACTIVE_TEACHER_USERNAME = 'SET_ADMIN_ACTIVE_TEACHER_USERNAME';
export const SET_ADMIN_ACTIVE_TEACHER_CLASSES = 'SET_ADMIN_ACTIVE_TEACHER_CLASSES';
export const SET_ADMIN_ACTIVE_TEACHER_CLASS_VALUE_INDEX = 'SET_ADMIN_ACTIVE_TEACHER_CLASS_VALUE_INDEX';
export const SET_ADMIN_TEACHER_DEPARTMENTS = 'SET_ADMIN_TEACHER_DEPARTMENTS';
export const SET_ADMIN_TEACHER_CLASS_VALUES = 'SET_ADMIN_TEACHER_CLASS_VALUES';
export const SET_ADMIN_INFOBOX = 'SET_ADMIN_INFOBOX';
export const SET_ADMIN_TEACHERS = 'SET_ADMIN_TEACHERS';
export const RESET_ADMIN_TEACHER_CLASS_VALUES = 'RESET_ADMIN_TEACHER_CLASS_VALUES';
export const RESET_ADMIN_DEFAULTS = 'RESET_ADMIN_DEFAULTS';

export const SET_STUDENT_ACTIVE_SEM='SET_STUDENT_ACTIVE_SEM';
export const SET_STUDENT_SEM_SUBJECT_VALUES='SET_STUDENT_SEM_SUBJECT_VALUES';
export const SET_STUDENT_SEMS='SET_STUDENT_SEMS';
export const SET_STUDENT_INFOBOX = 'SET_STUDENT_INFOBOX';
export const RESET_STUDENT_DEFAULTS = 'RESET_STUDENT_DEFAULTS';
export const SET_STUDENT_ACTIVE_SEM_SUBJECT_VALUE_INDEX = 'SET_STUDENT_ACTIVE_SEM_SUBJECT_VALUE_INDEX';
