export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SET_TEACHER_ACTIVE_COMPONENT = 'SET_TEACHER_ACTIVE_COMPONENT';
export const SET_TEACHER_ACTIVE_CLASS = 'SET_TEACHER_ACTIVE_CLASS';
export const SET_TEACHER_CLASSES = 'SET_TEACHER_CLASSES';
export const SET_TEACHER_CLASS_STUDENT_VALUES = 'SET_TEACHER_CLASS_STUDENT_VALUES';
export const UPDATE_TEACHER_CLASS_STUDENT_VALUES = 'UPDATE_TEACHER_CLASS_STUDENT_VALUES';
export const RESET_DEFAULTS_TEACHER = 'RESET_DEFAULTS_TEACHER';
export const SET_TEACHER_ACTIVE_CLASS_STUDENT_VALUE_INDEX = 'SET_TEACHER_ACTIVE_CLASS_STUDENT_VALUE_INDEX';

export const SET_ADMIN_TEACHERS = 'SET_ADMIN_TEACHERS';
export const SET_ADMIN_ACTIVE_COMPONENT = 'SET_ADMIN_ACTIVE_COMPONENT';
export const SET_ADMIN_TEACHER_CLASSES = 'SET_ADMIN_TEACHER_CLASSES';
export const SET_ADMIN_TEACHER_CLASSES_STUDENT_LIST = 'SET_ADMIN_TEACHER_CLASSES_STUDENT_LIST';
export const SET_ADMIN_ACTIVE_TEACHER = 'SET_ADMIN_ACTIVE_TEACHER';
export const SET_ADMIN_ACTIVE_CLASS = 'SET_ADMIN_ACTIVE_CLASS';
export const RESET_DEFAULTS_ADMIN = 'RESET_DEFAULTS_ADMIN';
export const SET_ADMIN_ACTIVE_TEACHER_CLASSES_INDEX = 'SET_ADMIN_ACTIVE_TEACHER_CLASSES_INDEX';
export const SET_ADMIN_ACTIVE_TEACHER_CLASSES_STUDENT_LIST_INDEX = 'SET_ADMIN_ACTIVE_TEACHER_CLASSES_STUDENT_LIST_INDEX';

export const SET_STUDENT_CURRENT_SEM='SET_STUDENT_CURRENT_SEM';
export const SET_STUDENT_MARKS='SET_STUDENT_MARKS';
export const SET_ACTIVE_PAGE='SET_ACTIVE_PAGE';
export const SET_SUBJECTS='SET_SUBJECTS';
