// const baseURI = 'https://immsnode.herokuapp.com';
// const baseURI2 = 'http://70877ff89f8d.ngrok.io';
const baseURI3 = 'https://still-wildwood-37648.herokuapp.com';
export const LOGIN = baseURI3+'/api/user/login';
// export const ASSIGN_TEACHER = baseURI+'/api/users/assignTeacher';
// export const ADD_TEACHER = baseURI+"/api/classes/addTeacher";
export const FETCH_CLASS_LIST = baseURI3+'/api/class/lecture/';
export const FETCH_CLASS_STUDENT_lIST = baseURI3+'/api/marks/class/';
// export const POST_MARKS = baseURI+'/api/record/class/';
export const FETCH_STUDENT_SEM_MARKS = baseURI3+'/api/marks/student/';
// export const STUDENT_MARKS = baseURI+'/api/marks/';
// export const FETCH_TEACHER_LIST = baseURI+'/api/users?role=teacher';
